export const Strings = {
    "app":'Avibra',
    "botName":'Arya',
    "login":'Login',
    "logIn":'Log In',    
    "signup":'Sign Up',
    "connectWith": 'Connect with',
    "signUpWith": 'Signu up with',
    "google": 'Google',
    "facebook":'Facebook',
    "email":'Email',
    "password":'Password',
    "begin":'Begin',
    "selectAddress":'Choose Address',
    "forgotPassword": 'Forgot Password?',
    "changePassword": 'Change Password',
    "verificationCode": 'Verification Code',
    "newPasswrod": 'New Password',
    "change": 'Change',
    "verify": 'Verify',
    "verifyAccount": 'Verify Account',
    "resendCode": 'Resend Code',
    "contribute": 'CONTRIBUTE',
    "claimReward": 'Claim Reward',
    "play": 'Play',
    "earned": "Earned",
    "quickTip": "Quick Tip",
    "rewardDetails": "Reward Details",
    "advertisement": "ADVERTISEMENT",
    "learnMore": "Learn More",
    "invite": "Invite",
    "inviteFriends": "Invite Friends",
    "givePermission": "Give Permission",
    "invited": "Invited",
    "connect": "Connect",
    "dataConnect": "Data Connect",
    "stayConnected": "Stay Connected",
    "disconnect" : "Disconnect",
    "takeQuiz": "Take Quiz"
};